FROM prom/prometheus:latest

# Copy Prometheus configuration file
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Use the official Prometheus entrypoint
CMD ["--config.file=/etc/prometheus/prometheus.yml"]
