# Use official Prometheus image
FROM prom/prometheus:2.46.0

# Copy Prometheus configuration file
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Expose Prometheus port
EXPOSE 9090

# Start Prometheus
CMD ["/bin/prometheus", "--config.file=/etc/prometheus/prometheus.yml"]
